# Generated by Django 3.2.5 on 2021-08-12 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuleTopic',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='Modify Time')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is Deleted')),
                ('title', models.CharField(max_length=20, verbose_name='title')),
                ('framework', models.IntegerField(choices=[(1, 'react'), (2, 'django')], verbose_name='framework')),
            ],
            options={
                'verbose_name': 'rule topic',
                'verbose_name_plural': 'rule topics',
            },
        ),
        migrations.CreateModel(
            name='RuleItem',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='Modify Time')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is Deleted')),
                ('item_type', models.IntegerField(choices=[(1, 'coding'), (2, 'testing')], verbose_name='item type')),
                ('content', models.CharField(max_length=250, verbose_name='content')),
                ('is_new', models.BooleanField(default=False, verbose_name='is new')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='standard.ruletopic', verbose_name='topic')),
            ],
            options={
                'verbose_name': 'rule item',
                'verbose_name_plural': 'rule items',
            },
        ),
    ]
