# Generated by Django 3.2.5 on 2021-11-06 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0002_alter_ruleitem_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruletopic',
            old_name='framework',
            new_name='type',
        ),
    ]
