# Generated by Django 3.2.5 on 2021-11-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0003_rename_framework_ruletopic_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruletopic',
            name='type',
            field=models.IntegerField(choices=[(1, 'react'), (2, 'django'), (3, 'po')], verbose_name='type'),
        ),
    ]
