# Generated by Django 3.2.5 on 2021-11-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0004_alter_ruletopic_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruletopic',
            old_name='type',
            new_name='rule_type',
        ),
    ]
