# Generated by Django 3.2.5 on 2021-11-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0005_rename_type_ruletopic_rule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruletopic',
            name='rule_type',
            field=models.IntegerField(choices=[(1, 'react'), (2, 'django'), (3, 'po')], verbose_name='rule type'),
        ),
    ]
