# Generated by Django 3.2.5 on 2021-11-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0006_alter_ruletopic_rule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleitem',
            name='item_type',
            field=models.IntegerField(blank=True, choices=[(1, 'coding'), (2, 'testing')], null=True, verbose_name='item type'),
        ),
    ]
